version: '3.8'

services:
  spark_ada_app:
    build:
      context: . # Build context is the root directory
      dockerfile: Dockerfile
    container_name: spark_ada_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      ADA_PROJECT_FILE: /app/spark_ada_project/main.gpr
      ADA_SOURCE_DIR: /app/spark_ada_project/src
    volumes:
      - ./spark_ada_project:/app/spark_ada_project:rw
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
